// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v6.30.2
// source: proto/restaurant.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'restaurant';

export interface OrderAcceptedDto {
  orderId: string;
  restaurantId: string;
}

export interface OrderAcceptedResponse {
  /** e.g., "true", "false" */
  status: boolean;
}

/** empty message */
export interface Empty {}

export interface RatingIncrease {
  restaurantId: string;
}

export interface RestaurantId {
  restaurantId: string;
}

export interface NameRequest {
  name: string;
}

export interface CuisineRequest {
  cuisine: string;
}

export interface UserIdRequest {
  userId: string;
}

export interface Coordinates {
  longitude: number;
  latitude: number;
}

export interface LocationRequest {
  latitude: number;
  longitude: number;
  radius: number;
}

export interface RestaurantList {
  restaurants: RestaurantResponse[];
}

export interface UpdateIsVerifiedRequest {
  restaurantId: string;
  isVerified: boolean;
}

export interface UpdateIsOpenRequest {
  restaurantId: string;
  isOpen: boolean;
}

/** Restaurant Data */
export interface RestaurantResponse {
  restaurantId: string;
  userId: string;
  name: string;
  address: string;
  location: Coordinates | undefined;
  phone: string;
  cuisineType: string;
  description: string;
  openHours: string;
  imageReference: string;
  numberOfRatings: number;
  isOpen: boolean;
  isVerified: boolean;
}

export interface CreateRestaurantRequest {
  userId: string;
  name: string;
  address: string;
  location: Coordinates | undefined;
  phone: string;
  cuisineType: string;
  description: string;
  openHours: string;
  imageReference: string;
}

export interface UpdateRestaurantRequest {
  restaurantId: string;
  name: string;
  address: string;
  location: Coordinates | undefined;
  phone: string;
  cuisineType: string;
  description: string;
  openHours: string;
  imageReference: string;
  isOpen: boolean;
  isVerified: boolean;
}

export const RESTAURANT_PACKAGE_NAME = 'restaurant';

/** rpc list */

export interface RestaurantServiceClient {
  createRestaurant(
    request: CreateRestaurantRequest,
  ): Observable<RestaurantResponse>;

  getRestaurant(request: RestaurantId): Observable<RestaurantResponse>;

  getAllRestaurants(request: Empty): Observable<RestaurantList>;

  updateRestaurant(
    request: UpdateRestaurantRequest,
  ): Observable<RestaurantResponse>;

  deleteRestaurant(request: RestaurantId): Observable<Empty>;

  getRestaurantByName(request: NameRequest): Observable<RestaurantResponse>;

  getRestaurantsByCuisine(request: CuisineRequest): Observable<RestaurantList>;

  getRestaurantsByUserId(request: UserIdRequest): Observable<RestaurantList>;

  updateIsVerified(
    request: UpdateIsVerifiedRequest,
  ): Observable<RestaurantResponse>;

  updateIsOpen(request: UpdateIsOpenRequest): Observable<RestaurantResponse>;

  getRestaurantsByLocation(
    request: LocationRequest,
  ): Observable<RestaurantList>;

  getAllRestaurantsWithFilters(request: Empty): Observable<RestaurantList>;

  updateRating(request: RatingIncrease): Observable<Empty>;

  decreaseRating(request: RestaurantId): Observable<Empty>;

  restaurantOrderAcceptOrReject(
    request: OrderAcceptedDto,
  ): Observable<OrderAcceptedResponse>;
}

/** rpc list */

export interface RestaurantServiceController {
  createRestaurant(
    request: CreateRestaurantRequest,
  ):
    | Promise<RestaurantResponse>
    | Observable<RestaurantResponse>
    | RestaurantResponse;

  getRestaurant(
    request: RestaurantId,
  ):
    | Promise<RestaurantResponse>
    | Observable<RestaurantResponse>
    | RestaurantResponse;

  getAllRestaurants(
    request: Empty,
  ): Promise<RestaurantList> | Observable<RestaurantList> | RestaurantList;

  updateRestaurant(
    request: UpdateRestaurantRequest,
  ):
    | Promise<RestaurantResponse>
    | Observable<RestaurantResponse>
    | RestaurantResponse;

  deleteRestaurant(
    request: RestaurantId,
  ): Promise<Empty> | Observable<Empty> | Empty;

  getRestaurantByName(
    request: NameRequest,
  ):
    | Promise<RestaurantResponse>
    | Observable<RestaurantResponse>
    | RestaurantResponse;

  getRestaurantsByCuisine(
    request: CuisineRequest,
  ): Promise<RestaurantList> | Observable<RestaurantList> | RestaurantList;

  getRestaurantsByUserId(
    request: UserIdRequest,
  ): Promise<RestaurantList> | Observable<RestaurantList> | RestaurantList;

  updateIsVerified(
    request: UpdateIsVerifiedRequest,
  ):
    | Promise<RestaurantResponse>
    | Observable<RestaurantResponse>
    | RestaurantResponse;

  updateIsOpen(
    request: UpdateIsOpenRequest,
  ):
    | Promise<RestaurantResponse>
    | Observable<RestaurantResponse>
    | RestaurantResponse;

  getRestaurantsByLocation(
    request: LocationRequest,
  ): Promise<RestaurantList> | Observable<RestaurantList> | RestaurantList;

  getAllRestaurantsWithFilters(
    request: Empty,
  ): Promise<RestaurantList> | Observable<RestaurantList> | RestaurantList;

  updateRating(
    request: RatingIncrease,
  ): Promise<Empty> | Observable<Empty> | Empty;

  decreaseRating(
    request: RestaurantId,
  ): Promise<Empty> | Observable<Empty> | Empty;

  restaurantOrderAcceptOrReject(
    request: RestaurantId,
  ):
    | Promise<OrderAcceptedResponse>
    | Observable<OrderAcceptedResponse>
    | OrderAcceptedResponse;
}

export function RestaurantServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'createRestaurant',
      'getRestaurant',
      'getAllRestaurants',
      'updateRestaurant',
      'deleteRestaurant',
      'getRestaurantByName',
      'getRestaurantsByCuisine',
      'getRestaurantsByUserId',
      'updateIsVerified',
      'updateIsOpen',
      'getRestaurantsByLocation',
      'getAllRestaurantsWithFilters',
      'updateRating',
      'decreaseRating',
      'restaurantOrderAcceptOrReject',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('RestaurantService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('RestaurantService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const RESTAURANT_SERVICE_NAME = 'RestaurantService';
